import type { Song, Playlist } from './types.d'

export const playlists: Playlist[] = [
	{
		id: 'link_in_park',
		title: 'This is Link In Park',
		color: '#fe9ca7',
		cover: '/music/link_in_park/cover.webp',
		genre: 'Nu-Metal',
		type: 'music',
		isAlbum: true,
		saved: false,
		public: true,
	},
	{
		id: 'rock_hits',
		title: 'Rock Hits',
		color: '#9D1B1D',
		cover: '/music/rock_hits/cover.webp',
		genre: 'Rock',
		type: 'music',
		isAlbum: true,
		saved: false,
		public: false,
	},
	{
		id: 'pop',
		title: 'Pop Essentials',
		color: '#F5632B',
		cover: '/music/pop/cover.webp',
		genre: 'Pop',
		type: 'music',
		isAlbum: true,
		saved: true,
		public: false,
	},
	{
		id: 'trap_vibes',
		title: 'Trap Vibes',
		color: '#0B0201',
		cover: '/music/trap_vibes/cover.webp',
		genre: 'Electronic',
		type: 'music',
		isAlbum: true,
		saved: true,
		public: false,
	},
	{
		id: 'electronic_dance',
		title: 'Electronic Dance',
		color: '#4F021D',
		cover: '/music/electronic_dance/cover.webp',
		genre: 'Electronic',
		type: 'music',
		isAlbum: true,
		saved: true,
		public: false,
	},
	{
		id: 'late_night_vibes',
		title: 'Late Night Vibes',
		color: '#91FE06',
		cover: '/music/late_night_vibes/cover.webp',
		genre: 'Chill',
		type: 'music',
		isAlbum: true,
		saved: false,
		public: false,
	},
	{
		id: 'summer_vibes',
		title: 'Summer Vibes',
		color: '#4DB8F4',
		cover: '/music/summer_vibes/cover.webp',
		genre: 'Pop',
		type: 'music',
		isAlbum: true,
		saved: true,
		public: false,
	},
	{
		id: 'avicii',
		title: 'Avicii',
		color: '#7A2986',
		cover: '/music/avicii/cover.webp',
		header: '/music/avicii/header.webp',
		genre: 'EDM',
		type: 'artist',
		isAlbum: false,
		saved: true,
		public: false,
	},
	{
		id: 'the_knowledge_hub',
		title: 'The Knowledge Hub',
		color: '#3A1253',
		cover: '/music/the_knowledge_hub/cover.webp',
		genre: 'Podcasts',
		type: 'podcast',
		isAlbum: true,
		saved: false,
		public: false,
	},
	{
		id: 'funky_grooves',
		title: 'Funky Grooves',
		color: '#E0C7AE',
		cover: '/music/funky_grooves/cover.webp',
		genre: 'Funk',
		type: 'music',
		isAlbum: true,
		saved: false,
		public: false,
	},
]

export const songs: Song[] = [
	{ id: 1, albumId: 'link_in_park', title: 'In the Bed', image: '/music/link_in_park/cover.webp', artists: ['Link In Park'], duration: '3:37', type: 'music' },
	{ id: 2, albumId: 'link_in_park', title: 'Thumb', image: '/music/link_in_park/cover.webp', artists: ['Link In Park'], duration: '3:08', type: 'music' },
	{ id: 3, albumId: 'link_in_park', title: 'The Impotence Machine', image: '/music/link_in_park/cover.webp', artists: ['Link In Park'], duration: '3:10', type: 'music' },
	{ id: 4, albumId: 'link_in_park', title: 'Paint', image: '/music/link_in_park/cover.webp', artists: ['Link In Park'], duration: '2:42', type: 'music' },
	{ id: 5, albumId: 'link_in_park', title: 'From the Outside', image: '/music/link_in_park/cover.webp', artists: ['Link In Park'], duration: '2:56', type: 'music' },
	{ id: 6, albumId: 'link_in_park', title: 'Crawling Back to Bed', image: '/music/link_in_park/cover.webp', artists: ['Link In Park'], duration: '3:28', type: 'music' },
	{ id: 7, albumId: 'link_in_park', title: 'Nobody Can Pay Me', image: '/music/link_in_park/cover.webp', artists: ['Link In Park'], duration: '3:46', type: 'music' },

	{ id: 8, albumId: 'rock_hits', title: 'Bohemian Rhapsody', image: '/music/rock_hits/cover.webp', artists: ['Queen'], duration: '5:55', type: 'music' },
	{ id: 9, albumId: 'rock_hits', title: 'Stairway to Heaven', image: '/music/rock_hits/cover.webp', artists: ['Led Zeppelin'], duration: '8:02', type: 'music' },
	{ id: 10, albumId: 'rock_hits', title: 'Livin\' on a Prayer', image: '/music/rock_hits/cover.webp', artists: ['Bon Jovi'], duration: '4:09', type: 'music' },
	{ id: 11, albumId: 'rock_hits', title: 'Sweet Child O\' Mine', image: '/music/rock_hits/cover.webp', artists: ['Guns N\' Roses'], duration: '5:56', type: 'music' },
	{ id: 12, albumId: 'rock_hits', title: 'Paint It Black', image: '/music/rock_hits/cover.webp', artists: ['The Rolling Stones'], duration: '3:45', type: 'music' },
	{ id: 13, albumId: 'rock_hits', title: 'Smoke on the Water', image: '/music/rock_hits/cover.webp', artists: ['Deep Purple'], duration: '5:40', type: 'music' },

	{ id: 14, albumId: 'summer_vibes', title: 'Shape of You', image: '/music/summer_vibes/cover.webp', artists: ['Ed Sheeran'], duration: '3:53', type: 'music' },
	{ id: 15, albumId: 'summer_vibes', title: 'Uptown Funk', image: '/music/summer_vibes/cover.webp', artists: ['Mark Ronson', 'Bruno Mars'], duration: '4:30', type: 'music' },
	{ id: 16, albumId: 'summer_vibes', title: 'Highest in the Room', image: '/music/summer_vibes/cover.webp', artists: ['Travis Scott'], duration: '4:00', type: 'music' },
	{ id: 17, albumId: 'summer_vibes', title: 'Can\'t Feel My Face', image: '/music/summer_vibes/cover.webp', artists: ['The Weeknd'], duration: '3: 35', type: 'music' },
	{ id: 18, albumId: 'summer_vibes', title: 'Circles', image: '/music/summer_vibes/cover.webp', artists: ['Post Malone'], duration: '3:35', type: 'music' },
	{ id: 19, albumId: 'summer_vibes', title: 'Physical', image: '/music/summer_vibes/cover.webp', artists: ['Dua Lipa'], duration: '3:13', type: 'music' },

	{ id: 20, albumId: 'late_night_vibes', title: 'Blinding Lights', image: '/music/late_night_vibes/cover.webp', artists: ['The Weeknd'], duration: '3:22', type: 'music' },
	{ id: 21, albumId: 'late_night_vibes', title: 'Sunflower', image: '/music/late_night_vibes/cover.webp', artists: ['Post Malone', 'Swae Lee'], duration: '2:38', type: 'music' },
	{ id: 22, albumId: 'late_night_vibes', title: 'Peaches', image: '/music/late_night_vibes/cover.webp', artists: ['Justin Bieber', 'Daniel Caesar', 'Giveon'], duration: '3:18', type: 'music' },
	{ id: 23, albumId: 'late_night_vibes', title: 'Adore You', image: '/music/late_night_vibes/cover.webp', artists: ['Harry Styles'], duration: '3:27', type: 'music' },

	{ id: 24, albumId: 'the_knowledge_hub', title: 'The Future of Artificial Intelligence', image: '/music/the_knowledge_hub/cover.webp', artists: ['Sofía Martínez', 'Carlos Gómez'], duration: '3:37', type: 'podcast' },
	{ id: 25, albumId: 'the_knowledge_hub', title: 'Demystifying Climate Change', image: '/music/the_knowledge_hub/cover.webp', artists: ['Laura Pérez'], duration: '3:14', type: 'podcast' },
	{ id: 26, albumId: 'the_knowledge_hub', title: 'The Secrets of Digital Marketing', image: '/music/the_knowledge_hub/cover.webp', artists: ['Juan Pérez', 'Ana Ruiz'], duration: '4:30', type: 'podcast' },
	{ id: 27, albumId: 'the_knowledge_hub', title: 'Exploring Space and Time', image: '/music/the_knowledge_hub/cover.webp', artists: ['Ricardo Gómez'], duration: '3:53', type: 'podcast' },
	{ id: 28, albumId: 'the_knowledge_hub', title: 'How Music Impacts Our Emotions', image: '/music/the_knowledge_hub/cover.webp', artists: ['Patricia López'], duration: '2:43', type: 'podcast' },
	{ id: 29, albumId: 'the_knowledge_hub', title: 'The Power of Human Resilience', image: '/music/the_knowledge_hub/cover.webp', artists: ['Marcos Díaz'], duration: '3:20', type: 'podcast' },
	{ id: 30, albumId: 'the_knowledge_hub', title: 'Stories that Define the World', image: '/music/the_knowledge_hub/cover.webp', artists: ['Valeria Mendoza', 'Eduardo Jiménez', 'Isabel Rodríguez'], duration: '3:18', type: 'podcast' },

	{ id: 31, albumId: 'trap_vibes', title: 'Sicko Mode', image: '/music/trap_vibes/cover.webp', artists: ['Travis Scott'], duration: '5:13', type: 'music' },
	{ id: 32, albumId: 'trap_vibes', title: 'Goosebumps', image: '/music/trap_vibes/cover.webp', artists: ['Travis Scott'], duration: '3:00', type: 'music' },
	{ id: 33, albumId: 'trap_vibes', title: 'Money Longer', image: '/music/trap_vibes/cover.webp', artists: ['Lil Uzi Vert'], duration: '2:45', type: 'music' },
	{ id: 34, albumId: 'trap_vibes', title: 'Bad and Boujee', image: '/music/trap_vibes/cover.webp', artists: ['Migos'], duration: '5:34', type: 'music' },
	{ id: 35, albumId: 'trap_vibes', title: 'XO Tour Llif3', image: '/music/trap_vibes/cover.webp', artists: ['Lil Uzi Vert'], duration: '3:00', type: 'music' },
	{ id: 36, albumId: 'trap_vibes', title: 'Panda', image: '/music/trap_vibes/cover.webp', artists: ['Desiigner'], duration: '3:25', type: 'music' },
	{ id: 37, albumId: 'trap_vibes', title: 'rockstar', image: '/music/trap_vibes/cover.webp', artists: ['Post Malone', '21 Savage'], duration: '3:38', type: 'music' },

	{ id: 38, albumId: 'pop', title: 'As It Was', image: '/music/pop/cover.webp', artists: ['Harry Styles'], duration: '2:47', type: 'music' },
	{ id: 39, albumId: 'pop', title: 'Levitating', image: '/music/pop/cover.webp', artists: ['Dua Lipa'], duration: '3:23', type: 'music' },
	{ id: 40, albumId: 'pop', title: 'Watermelon Sugar', image: '/music/pop/cover.webp', artists: ['Harry Styles'], duration: '2:54', type: 'music' },
	{ id: 41, albumId: 'pop', title: 'Don\'t Start Now', image: '/music/pop/cover.webp', artists: ['Dua Lipa'], duration: '3:03', type: 'music' },
	{ id: 42, albumId: 'pop', title: 'Bad Guy', image: '/music/pop/cover.webp', artists: ['Billie Eilish'], duration: '3:14', type: 'music' },
	{ id: 43, albumId: 'pop', title: 'Shallow', image: '/music/pop/cover.webp', artists: ['Lady Gaga', 'Bradley Cooper'], duration: '3:36', type: 'music' },
	{ id: 44, albumId: 'pop', title: 'Roar', image: '/music/pop/cover.webp', artists: ['Katy Perry'], duration: '3:42', type: 'music' },
	{ id: 45, albumId: 'pop', title: 'Can\'t Stop the Feeling!', image: '/music/pop/cover.webp', artists: ['Justin Timberlake'], duration: '3:56', type: 'music' },

	{ id: 46, albumId: 'electronic_dance', title: 'Faded', image: '/music/electronic_dance/cover.webp', artists: ['Alan Walker'], duration: '3:32', type: 'music' },
	{ id: 47, albumId: 'electronic_dance', title: 'Summer', image: '/music/electronic_dance/cover.webp', artists: ['Calvin Harris'], duration: '3:44', type: 'music' },
	{ id: 48, albumId: 'electronic_dance', title: 'Titanium', image: '/music/electronic_dance/cover.webp', artists: ['David Guetta', 'Sia'], duration: '4:05', type: 'music' },
	{ id: 49, albumId: 'electronic_dance', title: 'Scared to Be Lonely', image: '/music/electronic_dance/cover.webp', artists: ['Martin Garrix', 'Dua Lipa'], duration: '3:40', type: 'music' },
	{ id: 50, albumId: 'electronic_dance', title: 'Lean On', image: '/music/electronic_dance/cover.webp', artists: ['Major Lazer', 'DJ Snake', 'MØ'], duration: '2:56', type: 'music' },
	{ id: 51, albumId: 'electronic_dance', title: 'Happier', image: '/music/electronic_dance/cover.webp', artists: ['Marshmello', 'Bastille'], duration: '3:34', type: 'music' },
	{ id: 52, albumId: 'electronic_dance', title: 'Animals', image: '/music/electronic_dance/cover.webp', artists: ['Martin Garrix'], duration: '5:00', type: 'music' },
	{ id: 53, albumId: 'electronic_dance', title: 'On My Way', image: '/music/electronic_dance/cover.webp', artists: ['Alok', 'Bebe Rexha'], duration: '3:03', type: 'music' },

	{ id: 54, albumId: 'avicii', title: 'Wake Me Up', image: '/music/avicii/cover.webp', artists: ['Avicii'], duration: '4:07', type: 'music' },
	{ id: 55, albumId: 'avicii', title: 'Levels', image: '/music/avicii/cover.webp', artists: ['Avicii'], duration: '5:39', type: 'music' },
	{ id: 56, albumId: 'avicii', title: 'The Nights', image: '/music/avicii/cover.webp', artists: ['Avicii'], duration: '2:56', type: 'music' },
	{ id: 57, albumId: 'avicii', title: 'Hey Brother', image: '/music/avicii/cover.webp', artists: ['Avicii'], duration: '4:14', type: 'music' },
	{ id: 58, albumId: 'avicii', title: 'Waiting for Love', image: '/music/avicii/cover.webp', artists: ['Avicii'], duration: '3:49', type: 'music' },
	{ id: 59, albumId: 'avicii', title: 'Addicted to You', image: '/music/avicii/cover.webp', artists: ['Avicii'], duration: '2:28', type: 'music' },
	{ id: 60, albumId: 'avicii', title: 'Broken Arrows', image: '/music/avicii/cover.webp', artists: ['Avicii'], duration: '4:01', type: 'music' },
	{ id: 61, albumId: 'avicii', title: 'The Days', image: '/music/avicii/cover.webp', artists: ['Avicii'], duration: '4:40', type: 'music' },

	{ id: 62, albumId: 'funky_grooves', title: 'Get Lucky', image: '/music/funky_grooves/cover.webp', artists: ['Daft Punk', 'Pharrell Williams'], duration: '4:08', type: 'music' },
	{ id: 63, albumId: 'funky_grooves', title: '24K Magic', image: '/music/funky_grooves/cover.webp', artists: ['Bruno Mars'], duration: '3:46', type: 'music' },
	{ id: 64, albumId: 'funky_grooves', title: 'Happy', image: '/music/funky_grooves/cover.webp', artists: ['Pharrell Williams'], duration: '3:53', type: 'music' },
	{ id: 65, albumId: 'funky_grooves', title: 'Superstition', image: '/music/funky_grooves/cover.webp', artists: ['Stevie Wonder'], duration: '4:26', type: 'music' },
	{ id: 66, albumId: 'funky_grooves', title: 'Treasure', image: '/music/funky_grooves/cover.webp', artists: ['Bruno Mars'], duration: '3:00', type: 'music' },
]
