import type { Song, Playlist } from './types.d'

export const playlists: Playlist[] = [
	{
		id: 'link_in_park',
		title: 'This Is Link In Park',
		color: '#fe9ca7',
		cover: '/music/link_in_park/cover.webp',
		artists: ['Link In Park'],
		genre: 'Nu-Metal',
		type: 'music',
		isAlbum: true,
		saved: true,
	},
	{
		id: 'bread_sheeran',
		title: 'Bread Sheeran',
		color: '#d44630',
		cover: '/music/bread_sheeran/cover.webp',
		artists: ['Bread Sheeran'],
		genre: 'Pop',
		type: 'music',
		isAlbum: false,
		saved: false,
	},
	{
		id: 'toast_alone',
		title: 'Toast Alone',
		color: '#f9a825',
		cover: '/music/toast_alone/cover.webp',
		artists: ['Toast Alone'],
		genre: 'Hip-Hop',
		type: 'music',
		isAlbum: true,
		saved: false,
	},
	{
		id: 'em_and_em',
		title: 'The Em & Em Show',
		color: '#a41e22',
		cover: '/music/em_and_em/cover.webp',
		artists: ['Em & Em'],
		genre: 'Rap',
		type: 'music',
		isAlbum: true,
		saved: true,
	},
	{
		id: 'amichii',
		title: 'Amichii',
		color: '#60a5fa',
		cover: '/music/amichii/cover.webp',
		artists: ['Amichii'],
		genre: 'EDM',
		type: 'music',
		isAlbum: false,
		saved: true,
	},
]

export const songs: Song[] = [
	// Link In Park
	{ id: 1, albumId: 'link_in_park', title: 'In the Bed', image: '/music/link_in_park/cover.webp', artists: ['Link In Park'], duration: '3:37', type: 'music' },
	{ id: 2, albumId: 'link_in_park', title: 'Thumb', image: '/music/link_in_park/cover.webp', artists: ['Link In Park'], duration: '3:08', type: 'music' },
	{ id: 3, albumId: 'link_in_park', title: 'The Impotence Machine', image: '/music/link_in_park/cover.webp', artists: ['Link In Park'], duration: '3:10', type: 'music' },
	{ id: 4, albumId: 'link_in_park', title: 'Paint', image: '/music/link_in_park/cover.webp', artists: ['Link In Park'], duration: '2:42', type: 'music' },
	{ id: 5, albumId: 'link_in_park', title: 'From the Outside', image: '/music/link_in_park/cover.webp', artists: ['Link In Park'], duration: '2:56', type: 'music' },
	{ id: 6, albumId: 'link_in_park', title: 'Crawling Back to Bed', image: '/music/link_in_park/cover.webp', artists: ['Link In Park'], duration: '3:28', type: 'music' },
	{ id: 7, albumId: 'link_in_park', title: 'Nobody Can Pay Me', image: '/music/link_in_park/cover.webp', artists: ['Link In Park'], duration: '3:46', type: 'music' },

	// Bread Sheeran
	{ id: 8, albumId: 'bread_sheeran', title: 'Shape of Bread', image: '/music/bread_sheeran/cover.webp', artists: ['Bread Sheeran'], duration: '3:53', type: 'music' },
	{ id: 9, albumId: 'bread_sheeran', title: 'Perfect Slice', image: '/music/bread_sheeran/cover.webp', artists: ['Bread Sheeran'], duration: '4:22', type: 'music' },
	{ id: 10, albumId: 'bread_sheeran', title: 'Baguette on the Hill', image: '/music/bread_sheeran/cover.webp', artists: ['Bread Sheeran'], duration: '3:45', type: 'music' },
	{ id: 11, albumId: 'bread_sheeran', title: 'Breadagraph', image: '/music/bread_sheeran/cover.webp', artists: ['Bread Sheeran'], duration: '4:01', type: 'music' },
	{ id: 12, albumId: 'bread_sheeran', title: 'Toasting Out Loud', image: '/music/bread_sheeran/cover.webp', artists: ['Bread Sheeran'], duration: '4:17', type: 'music' },

	// Toast Alone
	{ id: 13, albumId: 'toast_alone', title: 'I need some help', image: '/music/toast_alone/cover.webp', artists: ['Toast Alone', 'Poorman Wallet'], duration: '2:58', type: 'music' },
	{ id: 14, albumId: 'toast_alone', title: 'Rockstar Crumbs', image: '/music/toast_alone/cover.webp', artists: ['Toast Alone'], duration: '4:12', type: 'music' },
	{ id: 15, albumId: 'toast_alone', title: 'Sunflower Seeds', image: '/music/toast_alone/cover.webp', artists: ['Toast Alone'], duration: '3:22', type: 'music' },
	{ id: 16, albumId: 'toast_alone', title: 'Butter Now', image: '/music/toast_alone/cover.webp', artists: ['Toast Alone'], duration: '3:50', type: 'music' },
	{ id: 17, albumId: 'toast_alone', title: 'Fortnite', image: '/music/toast_alone/cover.webp', artists: ['Toast Alone', 'Tail Or Swift'], duration: '2:58', type: 'music' },

	// Em & Em
	{ id: 18, albumId: 'em_and_em', title: 'Hate Myself', image: '/music/em_and_em/cover.webp', artists: ['Em & Em'], duration: '5:20', type: 'music' },
	{ id: 19, albumId: 'em_and_em', title: 'Stan Still', image: '/music/em_and_em/cover.webp', artists: ['Em & Em'], duration: '4:45', type: 'music' },
	{ id: 20, albumId: 'em_and_em', title: 'Kinda Afraid', image: '/music/em_and_em/cover.webp', artists: ['Em & Em'], duration: '3:55', type: 'music' },
	{ id: 21, albumId: 'em_and_em', title: 'The Fake Slim Shady', image: '/music/em_and_em/cover.webp', artists: ['Em & Em'], duration: '4:10', type: 'music' },
	{ id: 22, albumId: 'em_and_em', title: 'Without Me', image: '/music/em_and_em/cover.webp', artists: ['Em & Em'], duration: '4:05', type: 'music' },

	// Amichii
	{ id: 23, albumId: 'amichii', title: 'Wake You Up', image: '/music/amichii/cover.webp', artists: ['Amichii'], duration: '4:20', type: 'music' },
	{ id: 24, albumId: 'amichii', title: 'Hey StepBro', image: '/music/amichii/cover.webp', artists: ['Amichii'], duration: '3:50', type: 'music' },
	{ id: 25, albumId: 'amichii', title: 'Waiting for Hate', image: '/music/amichii/cover.webp', artists: ['Amichii'], duration: '4:00', type: 'music' },
	{ id: 26, albumId: 'amichii', title: 'Fixed Arrows', image: '/music/amichii/cover.webp', artists: ['Amichii'], duration: '3:45', type: 'music' },
	{ id: 27, albumId: 'amichii', title: 'The Evenings', image: '/music/amichii/cover.webp', artists: ['Amichii'], duration: '4:10', type: 'music' },
]

export const otherPlaylists: Playlist[] = [
	{
		id: 'electronic_party',
		title: 'Electronic Party',
		color: '#004AAF',
		artists: ['Avicii', 'Alok'],
		genre: 'Electronic',
		type: 'music',
		isAlbum: true,
		cover:
			'https://res.cloudinary.com/dp3ppkxo5/image/upload/v1693776174/spotify-astro/playlist_1_yci5uf.jpg',
		saved: false,
	},
	{
		id: 'trance',
		title: 'Trance',
		color: '#37A307',
		cover: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/v1693776174/spotify-astro/playlist_2_f9ymlx.jpg',
		artists: ['Tiesto', 'Armin Van Buuren'],
		genre: 'Electronic',
		type: 'music',
		isAlbum: true,
		saved: false,
	},
	{
		id: 'trap_vibes',
		title: 'Trap Vibes',
		color: '#DD5CD9',
		cover: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/v1693776175/spotify-astro/playlist_3_grshca.jpg',
		artists: ['Post Malone', 'Travis Scott', '21 savage'],
		genre: 'Electronic',
		type: 'music',
		isAlbum: true,
		saved: false,
	},
	{
		id: 'beatles_classics',
		title: 'Beatles Classics',
		color: '#DAD9C3',
		cover: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/v1693776175/spotify-astro/playlist_4_ap5xnb.jpg',
		artists: ['The Beatles'],
		genre: 'Electronic',
		type: 'music',
		isAlbum: true,
		saved: false,
	},
	{
		id: 'electronic_dance',
		title: 'Electronic Dance',
		color: '#FD3294',
		cover: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/v1693776175/spotify-astro/playlist_5_erjyb7.jpg',
		artists: ['Deadmau5'],
		genre: 'Electronic',
		type: 'music',
		isAlbum: true,
		saved: false,
	},
	{
		id: 'cow_songs',
		title: 'Cow songs',
		color: '#0C0B15',
		cover: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/v1693776474/spotify-astro/R-15112137-1586815179-1911_fsyl58.jpg',
		artists: ['Saint Hilda', 'Canada Buffalo'],
		genre: 'Electronic',
		type: 'music',
		isAlbum: true,
		saved: false,
	},
]

export const otherSongs: Song[] = [
	{
		id: 1,
		title: 'The Nights',
		image: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/w_40,h_40,c_scale/v1693776175/spotify-astro/song_1_qitfwl.jpg',
		artists: ['Avicii'],
		albumId: 'electronic_party',
		duration: '2:56',
		type: 'music',
	},
	{
		id: 2,
		title: 'Saint-Tropez',
		image: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/w_40,h_40,c_scale/v1693776175/spotify-astro/song_2_cijs8v.jpg',
		artists: ['Post Malone'],
		albumId: 'trap_vibes',
		duration: '2:23',
		type: 'music',
	},
	{
		id: 3,
		title: 'SICKO MODE',
		image: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/w_40,h_40,c_scale/v1693776176/spotify-astro/song_3_td9ncs.jpg',
		artists: ['Travis Scott', 'Drake'],
		albumId: 'trap_vibes',
		duration: '5:13',
		type: 'music',
	},
	{
		id: 4,
		title: 'Blinding Lights',
		image: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/w_40,h_40,c_scale/v1693776176/spotify-astro/song_4_lwumgu.png',
		artists: ['The Weeknd'],
		albumId: 'After Hours',
		duration: '3:22',
		type: 'music',
	},
	{
		id: 5,
		title: 'Shape of You',
		image: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/w_40,h_40,c_scale/v1693776175/spotify-astro/song_5_rd5xqa.jpg',
		artists: ['Ed Sheeran'],
		albumId: '÷ (Divide)',
		duration: '3:53',
		type: 'music',
	},
	{
		id: 6,
		title: 'Uptown Funk',
		image: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/w_40,h_40,c_scale/v1693776175/spotify-astro/song_6_f1lt7y.jpg',
		artists: ['Mark Ronson', 'Bruno Mars'],
		albumId: 'Uptown Special',
		duration: '4:30',
		type: 'music',
	},
	{
		id: 7,
		title: 'Bad Guy',
		image: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/w_40,h_40,c_scale/v1693776175/spotify-astro/song_7_m7f0mh.jpg',
		artists: ['Billie Eilish'],
		albumId: 'When We All Fall Asleep, Where Do We Go?',
		duration: '3:14',
		type: 'music',
	},
	{
		id: 8,
		title: 'Yesterday',
		image: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/w_40,h_40,c_scale/v1693776175/spotify-astro/song_8_hwxisr.jpg',
		artists: ['The Beatles'],
		albumId: 'beatles_classics',
		duration: '4:38',
		type: 'music',
	},
	{
		id: 9,
		title: 'Havana',
		image: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/w_40,h_40,c_scale/v1693776176/spotify-astro/song_9_szemzp.jpg',
		artists: ['Camila Cabello', 'Young Thug'],
		albumId: 'Camila',
		duration: '3:37',
		type: 'music',
	},
	{
		id: 10,
		title: 'Radioactive',
		image: 'https://res.cloudinary.com/dp3ppkxo5/image/upload/w_40,h_40,c_scale/v1693776176/spotify-astro/song_10_sz0cib.jpg',
		artists: ['Imagine Dragons'],
		albumId: 'Night Visions',
		duration: '3:07',
		type: 'music',
	},
]
