import type { Song, Playlist } from './types.d'

export const playlists: Playlist[] = [
	{
		id: 'link_in_park',
		title: 'This Is Link In Park',
		color: '#666666',
		cover: '/music/link_in_park/cover.webp',
		artists: ['Link In Park'],
		genre: 'Nu-Metal',
		description: '',
		isPublic: true,
		type: 'music',
		isAlbum: true,
		saved: true,
	},
	{
		id: 'bread_sheeran',
		title: 'Bread Sheeran',
		color: '#d44630',
		cover: '/music/bread_sheeran/cover.webp',
		artists: ['Bread Sheeran'],
		genre: 'Pop',
		description: '',
		isPublic: true,
		type: 'music',
		isAlbum: false,
		saved: false,
	},
	{
		id: 'toast_alone',
		title: 'Toast Alone',
		color: '#f9a825',
		cover: '/music/toast_alone/cover.webp',
		artists: ['Toast Alone'],
		genre: 'Hip-Hop',
		description: '',
		isPublic: true,
		type: 'music',
		isAlbum: true,
		saved: false,
	},
	{
		id: 'em_and_em',
		title: 'The Em & Em Show',
		color: '#a41e22',
		cover: '/music/em_and_em/cover.webp',
		artists: ['Em & Em'],
		genre: 'Rap',
		description: '',
		isPublic: true,
		type: 'music',
		isAlbum: true,
		saved: true,
	},
	{
		id: 'amichii',
		title: 'Amichii',
		color: '#3a6ea5',
		cover: '/music/amichii/cover.webp',
		artists: ['Amichii'],
		genre: 'EDM',
		description: '',
		isPublic: true,
		type: 'music',
		isAlbum: false,
		saved: true,
	},
	{
		id: 'deep_talks',
		title: 'Deep Talks',
		color: '#4e342e',
		artists: ['Dr. Lena Moore'],
		genre: 'Psychology',
		description: 'Exploraciones profundas sobre la mente y las emociones humanas.',
		isPublic: true,
		type: 'podcast',
		isAlbum: true,
		saved: false,
	},
	{
		id: 'bytecast',
		title: 'ByteCast Weekly',
		color: '#263238',
		artists: ['Tech Bros', 'CodeCast'],
		genre: 'Technology',
		description: 'Tu dosis semanal de tecnología, startups y curiosidades digitales.',
		isPublic: true,
		type: 'podcast',
		isAlbum: true,
		saved: false,
	},
]

export const songs: Song[] = [
	// Link In Park
	{
		id: 1,
		albumId: 'link_in_park',
		title: 'In the Bed',
		image: '/music/link_in_park/cover.webp',
		artists: ['Link In Park'],
		duration: '3:45',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 2,
		albumId: 'link_in_park',
		title: 'Thumb',
		image: '/music/link_in_park/cover.webp',
		artists: ['Link In Park'],
		duration: '3:06',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 3,
		albumId: 'link_in_park',
		title: 'The Impotence Machine',
		image: '/music/link_in_park/cover.webp',
		artists: ['Link In Park'],
		duration: '4:01',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 4,
		albumId: 'link_in_park',
		title: 'Paint',
		image: '/music/link_in_park/cover.webp',
		artists: ['Link In Park'],
		duration: '3:28',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 5,
		albumId: 'link_in_park',
		title: 'From the Outside',
		image: '/music/link_in_park/cover.webp',
		artists: ['Link In Park'],
		duration: '3:38',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 6,
		albumId: 'link_in_park',
		title: 'Crawling Back to Bed',
		image: '/music/link_in_park/cover.webp',
		artists: ['Link In Park'],
		duration: '2:54',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 7,
		albumId: 'link_in_park',
		title: 'Nobody Can Pay Me',
		image: '/music/link_in_park/cover.webp',
		artists: ['Link In Park'],
		duration: '3:42',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},

	// Bread Sheeran
	{
		id: 1,
		albumId: 'bread_sheeran',
		title: 'Shape of Cheese',
		image: '/music/bread_sheeran/cover.webp',
		artists: ['Bread Sheeran'],
		duration: '3:53',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 2,
		albumId: 'bread_sheeran',
		title: 'Perfect Slice',
		image: '/music/bread_sheeran/cover.webp',
		artists: ['Bread Sheeran'],
		duration: '4:22',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 3,
		albumId: 'bread_sheeran',
		title: 'Cheddar on the Hill',
		image: '/music/bread_sheeran/cover.webp',
		artists: ['Bread Sheeran'],
		duration: '3:45',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 4,
		albumId: 'bread_sheeran',
		title: 'Cheddagraph',
		image: '/music/bread_sheeran/cover.webp',
		artists: ['Bread Sheeran'],
		duration: '4:01',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 5,
		albumId: 'bread_sheeran',
		title: 'Stinking Out Loud',
		image: '/music/bread_sheeran/cover.webp',
		artists: ['Bread Sheeran'],
		duration: '4:17',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},

	// Toast Alone
	{
		id: 1,
		albumId: 'toast_alone',
		title: 'I need some help',
		image: '/music/toast_alone/cover.webp',
		artists: ['Toast Alone', 'Poorman Wallet'],
		duration: '2:58',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 2,
		albumId: 'toast_alone',
		title: 'Rockstar Crumbs',
		image: '/music/toast_alone/cover.webp',
		artists: ['Toast Alone'],
		duration: '4:12',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 3,
		albumId: 'toast_alone',
		title: 'Sunflower Seeds',
		image: '/music/toast_alone/cover.webp',
		artists: ['Toast Alone'],
		duration: '3:22',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 4,
		albumId: 'toast_alone',
		title: 'Butter Now',
		image: '/music/toast_alone/cover.webp',
		artists: ['Toast Alone'],
		duration: '3:50',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 5,
		albumId: 'toast_alone',
		title: 'Fortnite',
		image: '/music/toast_alone/cover.webp',
		artists: ['Toast Alone', 'Tail Or Swift'],
		duration: '2:58',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},

	// Em & Em
	{
		id: 1,
		albumId: 'em_and_em',
		title: 'Hate Myself',
		image: '/music/em_and_em/cover.webp',
		artists: ['Em & Em'],
		duration: '5:20',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 2,
		albumId: 'em_and_em',
		title: 'Stan Still',
		image: '/music/em_and_em/cover.webp',
		artists: ['Em & Em'],
		duration: '4:45',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 3,
		albumId: 'em_and_em',
		title: 'Kinda Afraid',
		image: '/music/em_and_em/cover.webp',
		artists: ['Em & Em'],
		duration: '3:55',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 4,
		albumId: 'em_and_em',
		title: 'The Fake Slim Shady',
		image: '/music/em_and_em/cover.webp',
		artists: ['Em & Em'],
		duration: '4:10',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 5,
		albumId: 'em_and_em',
		title: 'Without Me',
		image: '/music/em_and_em/cover.webp',
		artists: ['Em & Em'],
		duration: '4:05',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},

	// Amichii
	{
		id: 1,
		albumId: 'amichii',
		title: 'Wake You Up',
		image: '/music/amichii/cover.webp',
		artists: ['Amichii'],
		duration: '4:20',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 2,
		albumId: 'amichii',
		title: 'Hey StepBro',
		image: '/music/amichii/cover.webp',
		artists: ['Amichii'],
		duration: '3:50',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 3,
		albumId: 'amichii',
		title: 'Waiting for Hate',
		image: '/music/amichii/cover.webp',
		artists: ['Amichii'],
		duration: '4:00',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 4,
		albumId: 'amichii',
		title: 'Fixed Arrows',
		image: '/music/amichii/cover.webp',
		artists: ['Amichii'],
		duration: '3:45',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
	{
		id: 5,
		albumId: 'amichii',
		title: 'The Evenings',
		image: '/music/amichii/cover.webp',
		artists: ['Amichii'],
		duration: '4:10',
		explicit: false,
		previewUrl: '',
		type: 'music',
	},
]
